#cloud-config

package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent
  - git
  - figlet
runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - git clone https://github.com/realcryptonight/debian-install-scripts.git
  - cd debian-install-scripts/
  - chmod 755 setup-standard.sh
  - ./setup-standard.sh