#!/bin/bash
#
#    10-sysinfo - generate the system information
#    Copyright (c) 2013 Nick Charlton
#
#    Authors: Nick Charlton <hello@nickcharlton.net>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# 	 Modified by Daniel Markink

red="\e[31m"
default="\e[39m"
white="\e[97m"
green="\e[32m"

ipv4=`hostname -I | awk '{print $1}'`
ipv6=`hostname -I | awk '{print $2}'`

date=`date`
load=`cat /proc/loadavg | awk '{print $1}'`
memory_usage=`free -m | awk '/Mem/ { printf("%3.1f%%", $3/$2*100) }'`

uptime=`uptime | grep -ohe 'up .*' | sed 's/,/\ hours/g' | awk '{ printf $2" "$3 }'`
processes=`ps aux | wc -l`
 
printf "%bSystem information as of%b: %b%s\n" "$green" "$white" "$default" "$date"
echo
printf "%bIPv4 Address%b:%b\t%s\t%bIPv6 Address%b:%b\t%s\n" "$red" "$white" "$default" "$ipv4" "$red" "$white" "$default" "$ipv6"
printf "%bSystem Load%b:%b\t%s\t\t%bMemory Usage%b:%b\t%s\n" "$red" "$white" "$default" "$load" "$red" "$white" "$default" "$memory_usage"
printf "%bProcesses%b:%b\t%s\t\t%bSystem Uptime%b:%b\t%s\n" "$red" "$white" "$default" "$processes" "$red" "$white" "$default" "$uptime"
echo
