#!/bin/bash
#
#    10-sysinfo - generate the system information
#    Copyright (c) 2013 Nick Charlton
#
#    Authors: Nick Charlton <hello@nickcharlton.net>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# 	 Modified by Daniel Markink

red="\e[31m"
default="\e[39m"
white="\e[97m"
green="\e[32m"

ipv4=`hostname -I | awk '{print $1}'`
ipv6=`hostname -I | awk '{print $2}'`

date=`date`
load=`cat /proc/loadavg | awk '{print $1}'`
memory_usage=`free -m | awk '/Mem/ { printf("%3.1f%%", $3/$2*100) }'`

uptime=`uptime | grep -ohe 'up .*' | sed 's/,/\ hours/g' | awk '{ printf $2" "$3 }'`
processes=`ps aux | wc -l`

root_usage=`df -h / | awk '/\// {print $(NF-1)}'`
root_free_space=`df -h / | awk '/\// {print $(NF-4)}'`
 
printf "System information as of: $date \n"
echo
printf "IPv4 Address:\t%s\tIPv6 Address:\t%s\n" $ipv4 $ipv6
printf "System Load:\t%s\t\tMemory Usage:\t%s\n" $load $memory_usage
printf "Processes:\t%s\t\tSystem Uptime:\t%s\n" $processes $uptime
echo
printf "Disk information as of: $date \n"
echo
printf "Usage On /:\t\t%s\tFree On /:\t\t%s\n" $root_usage $root_free_space
echo